/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BackupFeed__factory } from './BackupFeed__factory.js';
export { IAutoPriceFeed__factory } from './IAutoPriceFeed__factory.js';