/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IAutoPriceFeedInterface extends Interface {
    getFunction(nameOrSignature: "ethPrice" | "getETHPrice" | "isDataFresh" | "lastUpdate" | "updateETHPrice"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'ethPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'getETHPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'isDataFresh', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastUpdate', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateETHPrice', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'ethPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getETHPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDataFresh', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastUpdate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateETHPrice', data: BytesLike): Result;
  }

  

  export interface IAutoPriceFeed extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAutoPriceFeed;
    waitForDeployment(): Promise<this>;

    interface: IAutoPriceFeedInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ethPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getETHPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isDataFresh: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lastUpdate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateETHPrice: TypedContractMethod<
      [_newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ethPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getETHPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isDataFresh'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastUpdate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateETHPrice'): TypedContractMethod<
      [_newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }