/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAutoPriceFeed } from './IAutoPriceFeed.js';
export type { MultiUpdater } from './MultiUpdater.js';