/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as autoPriceFeedSol from './AutoPriceFeed.sol/index.js';
export * as backupSol from './Backup.sol/index.js';
export * as iAutoPriceFeedSol from './IAutoPriceFeed.sol/index.js';