/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AutoPriceFeedInterface extends Interface {
    getFunction(nameOrSignature: "changeOwner" | "ethPrice" | "ethPrices" | "getETHPrice" | "isDataFresh" | "lastUpdate" | "owner" | "updateETHPrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PriceUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'changeOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'ethPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'ethPrices', values?: undefined): string;
encodeFunctionData(functionFragment: 'getETHPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'isDataFresh', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastUpdate', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateETHPrice', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'changeOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getETHPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDataFresh', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastUpdate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateETHPrice', data: BytesLike): Result;
  }

  
    export namespace PriceUpdatedEvent {
      export type InputTuple = [newPrice: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [newPrice: bigint, timestamp: bigint];
      export interface OutputObject {newPrice: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AutoPriceFeed extends BaseContract {
    
    connect(runner?: ContractRunner | null): AutoPriceFeed;
    waitForDeployment(): Promise<this>;

    interface: AutoPriceFeedInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    changeOwner: TypedContractMethod<
      [_newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    ethPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ethPrices: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getETHPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isDataFresh: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lastUpdate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updateETHPrice: TypedContractMethod<
      [_newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'changeOwner'): TypedContractMethod<
      [_newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ethPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ethPrices'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getETHPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isDataFresh'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastUpdate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateETHPrice'): TypedContractMethod<
      [_newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PriceUpdated'): TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;

    filters: {
      
      'PriceUpdated(int256,uint256)': TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
      PriceUpdated: TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
    
    };
  }