/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AutoPriceFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AutoPriceFeed__factory>
getContractFactory(name: 'BackupFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BackupFeed__factory>
getContractFactory(name: 'IAutoPriceFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAutoPriceFeed__factory>
getContractFactory(name: 'IAutoPriceFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAutoPriceFeed__factory>
getContractFactory(name: 'MultiUpdater', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MultiUpdater__factory>

  getContractAt(name: 'AutoPriceFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AutoPriceFeed>
getContractAt(name: 'BackupFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BackupFeed>
getContractAt(name: 'IAutoPriceFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAutoPriceFeed>
getContractAt(name: 'IAutoPriceFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAutoPriceFeed>
getContractAt(name: 'MultiUpdater', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MultiUpdater>

  deployContract(name: 'AutoPriceFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AutoPriceFeed>
deployContract(name: 'BackupFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BackupFeed>
deployContract(name: 'IAutoPriceFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAutoPriceFeed>
deployContract(name: 'IAutoPriceFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAutoPriceFeed>
deployContract(name: 'MultiUpdater', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MultiUpdater>

  deployContract(name: 'AutoPriceFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AutoPriceFeed>
deployContract(name: 'BackupFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BackupFeed>
deployContract(name: 'IAutoPriceFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAutoPriceFeed>
deployContract(name: 'IAutoPriceFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAutoPriceFeed>
deployContract(name: 'MultiUpdater', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MultiUpdater>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  