/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as autoPriceFeedSol from './AutoPriceFeed.sol/index.js';
export type { autoPriceFeedSol };
import type * as backupSol from './Backup.sol/index.js';
export type { backupSol };
import type * as iAutoPriceFeedSol from './IAutoPriceFeed.sol/index.js';
export type { iAutoPriceFeedSol };
export * as factories from './factories/index.js';
export type { AutoPriceFeed } from './AutoPriceFeed.sol/AutoPriceFeed.js';
export { AutoPriceFeed__factory } from './factories/AutoPriceFeed.sol/AutoPriceFeed__factory.js';
export type { BackupFeed } from './Backup.sol/BackupFeed.js';
export { BackupFeed__factory } from './factories/Backup.sol/BackupFeed__factory.js';
export type { IAutoPriceFeed } from './Backup.sol/IAutoPriceFeed.js';
export { IAutoPriceFeed__factory } from './factories/Backup.sol/IAutoPriceFeed__factory.js';
export type { MultiUpdater } from './IAutoPriceFeed.sol/MultiUpdater.js';
export { MultiUpdater__factory } from './factories/IAutoPriceFeed.sol/MultiUpdater__factory.js';