/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface BackupFeedInterface extends Interface {
    getFunction(nameOrSignature: "emergencyUpdate" | "mainFeed" | "owner" | "updateFromChainlink"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BackupUpdate"): EventFragment;

    encodeFunctionData(functionFragment: 'emergencyUpdate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mainFeed', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateFromChainlink', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'emergencyUpdate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mainFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFromChainlink', data: BytesLike): Result;
  }

  
    export namespace BackupUpdateEvent {
      export type InputTuple = [price: BigNumberish];
      export type OutputTuple = [price: bigint];
      export interface OutputObject {price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BackupFeed extends BaseContract {
    
    connect(runner?: ContractRunner | null): BackupFeed;
    waitForDeployment(): Promise<this>;

    interface: BackupFeedInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    emergencyUpdate: TypedContractMethod<
      [_price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mainFeed: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    updateFromChainlink: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'emergencyUpdate'): TypedContractMethod<
      [_price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mainFeed'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'updateFromChainlink'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BackupUpdate'): TypedContractEvent<BackupUpdateEvent.InputTuple, BackupUpdateEvent.OutputTuple, BackupUpdateEvent.OutputObject>;

    filters: {
      
      'BackupUpdate(int256)': TypedContractEvent<BackupUpdateEvent.InputTuple, BackupUpdateEvent.OutputTuple, BackupUpdateEvent.OutputObject>;
      BackupUpdate: TypedContractEvent<BackupUpdateEvent.InputTuple, BackupUpdateEvent.OutputTuple, BackupUpdateEvent.OutputObject>;
    
    };
  }